import type { PdfLang, PdfStrings } from "./types";

export const PDF_STRINGS: Record<PdfLang, PdfStrings> = {
  fr: {
    quote: "DEVIS",
    invoice: "FACTURE",
    date: "Date",
    client: "Client",
    designation: "Désignation",
    qty: "Qté",
    unitPrice: "P.U.",
    total: "Total",
    totalTtc: "Total TTC",
    subtotal: "Sous-total",
    discount: "Remise",
    netAmount: "Montant HT",
    vat: "TVA",
    vatNa: "TVA non applicable",
    conditions: "Conditions",
    signature: "Signature",
    approval: "Bon pour accord",
    approvalDate: "Date et signature du client",
    quoteValidity: "Devis valable 30 jours à compter de la date d'émission.",
    latePenalty:
      "Tout retard de paiement entraîne des pénalités au taux légal en vigueur (art. OHADA).",
    regime: "Régime",
    footer: "Généré avec DIGICK Devis",
  },
  en: {
    quote: "QUOTE",
    invoice: "INVOICE",
    date: "Date",
    client: "Client",
    designation: "Description",
    qty: "Qty",
    unitPrice: "Unit",
    total: "Total",
    totalTtc: "Total incl. VAT",
    subtotal: "Subtotal",
    discount: "Discount",
    netAmount: "Net amount",
    vat: "VAT",
    vatNa: "VAT not applicable",
    conditions: "Terms",
    signature: "Signature",
    approval: "Approved for agreement",
    approvalDate: "Client date and signature",
    quoteValidity: "Quote valid for 30 days from the date of issue.",
    latePenalty:
      "Late payment incurs penalties at the applicable legal rate (OHADA).",
    regime: "Regime",
    footer: "Generated with DIGICK Devis",
  },
};
